[package]

name = "genprime-rust"
version = "0.1.0"
authors = [ "Eddie Ringle <eddie@ringle.io>" ]
license = "BSD-3-Clause"

[[bin]]

name = "genprime-rust"
path = "genprime.rs"

[dependencies]

time = "*"
